import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../app/_components/Header";
import Footer from "./_components/Footer";
import { Cairo } from "next/font/google";
import { Toaster } from "../components/ui/sonner";

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choisis les poids que tu veux
  variable: "--font-cairo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Doctor Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={geistSans.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:px-20 py-3`}
      >
        <div className="md:px-20">
          <Header />
        </div>
        {children}
        {}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
